baseURL = 'https://lrullo0.github.io/'
languageCode = 'es'
title = 'UOC - Luca Rullo'
theme = 'mini'
enableRobotsTXT = true

[taxonomies]
  category = 'categories'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  colorTheme = "blue"
  dateFormat = "02 Jan 2006"
  custom_css = ["css/custom.css"]
