baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'simplog'
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  colorTheme = "blue"
